import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram, SYSVAR_RENT_PUBKEY } from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  createMint,
  createAccount,
  mintTo,
  getAccount,
} from "@solana/spl-token";
import { expect } from "chai";

// Helper function to add delay between requests (avoid rate limiting)
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Import the program type - will be generated by anchor build
// For now, we use any type and define our own interfaces
interface AgoraProgram extends Program {
  methods: {
    initializeAgentProfile: (name: string) => any;
    postTask: (
      title: string,
      description: string,
      budget: anchor.BN,
      milestones: Milestone[],
      deadline: anchor.BN
    ) => any;
    updateTask: (
      description: string | null,
      budget: anchor.BN | null,
      deadline: anchor.BN | null
    ) => any;
    cancelTask: () => any;
    submitBid: (
      amount: anchor.BN,
      timeline: anchor.BN,
      proposal: string
    ) => any;
    acceptBid: () => any;
    rejectBid: () => any;
    withdrawBid: () => any;
    fundEscrow: () => any;
    completeMilestone: (milestoneIndex: number) => any;
    releasePayment: (milestoneIndex: number) => any;
    requestRefund: () => any;
    submitReview: (rating: number, reviewText: string) => any;
  };
  account: {
    agentProfile: {
      fetch: (address: PublicKey) => Promise<AgentProfile>;
    };
    task: {
      fetch: (address: PublicKey) => Promise<Task>;
    };
    bid: {
      fetch: (address: PublicKey) => Promise<Bid>;
    };
    escrow: {
      fetch: (address: PublicKey) => Promise<Escrow>;
    };
    review: {
      fetch: (address: PublicKey) => Promise<Review>;
    };
  };
}

// Account state interfaces
interface AgentProfile {
  owner: PublicKey;
  name: string;
  tasksPosted: number;
  tasksCompleted: number;
  totalEarned: anchor.BN;
  totalSpent: anchor.BN;
  ratingSum: number;
  ratingCount: number;
  createdAt: anchor.BN;
}

interface Milestone {
  description: string;
  amount: anchor.BN;
  completed: boolean;
  paid: boolean;
}

type TaskStatus = { open: {} } | { inProgress: {} } | { completed: {} } | { cancelled: {} } | { disputed: {} };

interface Task {
  owner: PublicKey;
  title: string;
  description: string;
  budget: anchor.BN;
  milestones: Milestone[];
  deadline: anchor.BN;
  status: TaskStatus;
  acceptedBid: PublicKey | null;
  escrowAccount: PublicKey | null;
  createdAt: anchor.BN;
  updatedAt: anchor.BN;
}

type BidStatus = { pending: {} } | { accepted: {} } | { rejected: {} } | { withdrawn: {} };

interface Bid {
  task: PublicKey;
  bidder: PublicKey;
  amount: anchor.BN;
  timeline: anchor.BN;
  proposal: string;
  status: BidStatus;
  createdAt: anchor.BN;
}

interface Escrow {
  task: PublicKey;
  client: PublicKey;
  freelancer: PublicKey;
  totalAmount: anchor.BN;
  releasedAmount: anchor.BN;
  tokenMint: PublicKey;
  bump: number;
}

interface Review {
  reviewer: PublicKey;
  reviewee: PublicKey;
  task: PublicKey;
  rating: number;
  reviewText: string;
  createdAt: anchor.BN;
}

// Helper function to get discriminant from status object
function getTaskStatus(status: TaskStatus): string {
  if ('open' in status) return 'Open';
  if ('inProgress' in status) return 'InProgress';
  if ('completed' in status) return 'Completed';
  if ('cancelled' in status) return 'Cancelled';
  if ('disputed' in status) return 'Disputed';
  return 'Unknown';
}

function getBidStatus(status: BidStatus): string {
  if ('pending' in status) return 'Pending';
  if ('accepted' in status) return 'Accepted';
  if ('rejected' in status) return 'Rejected';
  if ('withdrawn' in status) return 'Withdrawn';
  return 'Unknown';
}

describe("Agora - Agent Task Marketplace", () => {
  // Configure the client to use the local cluster
  anchor.setProvider(anchor.AnchorProvider.env());
  const provider = anchor.getProvider() as anchor.AnchorProvider;
  
  // Load the program
  const program = anchor.workspace.Agora as AgoraProgram;
  
  // Constants for testing
  const MAX_TITLE_LEN = 100;
  const MAX_DESC_LEN = 5000;
  const MAX_MILESTONES = 10;
  const MAX_PROPOSAL_LEN = 2000;
  const MAX_NAME_LEN = 50;
  const MAX_REVIEW_LEN = 1000;

  // ============================================================================
  // AGENT PROFILE TESTS
  // ============================================================================
  
  describe("Agent Profile", () => {
    it("should initialize an agent profile with valid name", async () => {
      // Generate a new keypair for the agent
      const agent = Keypair.generate();
      
      // Airdrop SOL for transaction fees
      const sig = await provider.connection.requestAirdrop(
        agent.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500); // Delay to avoid rate limiting
      
      // Derive PDA for profile
      const [profilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), agent.publicKey.toBuffer()],
        program.programId
      );
      
      // Initialize profile
      const name = "Alice Agent";
      await program.methods
        .initializeAgentProfile(name)
        .accounts({
          owner: agent.publicKey,
          profile: profilePda,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();
      
      // Verify profile was created correctly
      const profile = await program.account.agentProfile.fetch(profilePda);
      expect(profile.owner.toBase58()).to.equal(agent.publicKey.toBase58());
      expect(profile.name).to.equal(name);
      expect(profile.tasksPosted).to.equal(0);
      expect(profile.tasksCompleted).to.equal(0);
      expect(profile.totalEarned.toNumber()).to.equal(0);
      expect(profile.totalSpent.toNumber()).to.equal(0);
      expect(profile.ratingSum).to.equal(0);
      expect(profile.ratingCount).to.equal(0);
      expect(profile.createdAt.toNumber()).to.be.greaterThan(0);
    });

    it("should fail to initialize profile with empty name", async () => {
      const agent = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        agent.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      const [profilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), agent.publicKey.toBuffer()],
        program.programId
      );
      
      try {
        await program.methods
          .initializeAgentProfile("")
          .accounts({
            owner: agent.publicKey,
            profile: profilePda,
            systemProgram: SystemProgram.programId,
          })
          .signers([agent])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("NameTooLong");
      }
    });

    it("should fail to initialize profile with name exceeding max length", async () => {
      const agent = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        agent.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      const [profilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), agent.publicKey.toBuffer()],
        program.programId
      );
      
      const longName = "a".repeat(MAX_NAME_LEN + 1);
      
      try {
        await program.methods
          .initializeAgentProfile(longName)
          .accounts({
            owner: agent.publicKey,
            profile: profilePda,
            systemProgram: SystemProgram.programId,
          })
          .signers([agent])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("NameTooLong");
      }
    });

    it("should fail to initialize duplicate profile for same owner", async () => {
      const agent = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        agent.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      const [profilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), agent.publicKey.toBuffer()],
        program.programId
      );
      
      // First initialization should succeed
      await program.methods
        .initializeAgentProfile("First Profile")
        .accounts({
          owner: agent.publicKey,
          profile: profilePda,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();
      
      // Second initialization should fail
      try {
        await program.methods
          .initializeAgentProfile("Second Profile")
          .accounts({
            owner: agent.publicKey,
            profile: profilePda,
            systemProgram: SystemProgram.programId,
          })
          .signers([agent])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("custom program error");
      }
    });
  });

  // ============================================================================
  // TASK POSTING TESTS
  // ============================================================================
  
  describe("Task Posting", () => {
    let client: Keypair;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      client = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        client.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500); // Delay to avoid rate limiting
      
      milestones = [
        {
          description: "Initial setup and planning",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
        {
          description: "Development phase",
          amount: new anchor.BN(2000000),
          completed: false,
          paid: false,
        },
        {
          description: "Testing and delivery",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
      ];
    });

    it("should post a task with valid parameters", async () => {
      const task = Keypair.generate();
      const title = "Build a Solana dApp";
      const description = "Create a decentralized application on Solana blockchain with specific features";
      const budget = new anchor.BN(4000000);
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7); // 7 days from now
      
      await program.methods
        .postTask(title, description, budget, milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: task.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, task])
        .rpc();
      
      // Verify task was created
      const taskAccount = await program.account.task.fetch(task.publicKey);
      expect(taskAccount.owner.toBase58()).to.equal(client.publicKey.toBase58());
      expect(taskAccount.title).to.equal(title);
      expect(taskAccount.description).to.equal(description);
      expect(taskAccount.budget.toNumber()).to.equal(budget.toNumber());
      expect(taskAccount.milestones.length).to.equal(3);
      expect(taskAccount.deadline.toNumber()).to.equal(deadline.toNumber());
      expect(getTaskStatus(taskAccount.status)).to.equal("Open");
      expect(taskAccount.acceptedBid).to.be.null;
      expect(taskAccount.escrowAccount).to.be.null;
    });

    it("should fail to post task with empty title", async () => {
      const task = Keypair.generate();
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      
      try {
        await program.methods
          .postTask("", "Description", new anchor.BN(1000000), milestones, deadline)
          .accounts({
            owner: client.publicKey,
            task: task.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, task])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("EmptyTitle");
      }
    });

    it("should fail to post task with title exceeding max length", async () => {
      const task = Keypair.generate();
      const longTitle = "a".repeat(MAX_TITLE_LEN + 1);
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      
      try {
        await program.methods
          .postTask(longTitle, "Description", new anchor.BN(1000000), milestones, deadline)
          .accounts({
            owner: client.publicKey,
            task: task.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, task])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("TitleTooLong");
      }
    });

    it("should fail to post task with description exceeding max length", async () => {
      const task = Keypair.generate();
      const longDescription = "a".repeat(MAX_DESC_LEN + 1);
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      
      try {
        await program.methods
          .postTask("Title", longDescription, new anchor.BN(1000000), milestones, deadline)
          .accounts({
            owner: client.publicKey,
            task: task.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, task])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("DescriptionTooLong");
      }
    });

    it("should fail to post task with no milestones", async () => {
      const task = Keypair.generate();
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      
      try {
        await program.methods
          .postTask("Title", "Description", new anchor.BN(1000000), [], deadline)
          .accounts({
            owner: client.publicKey,
            task: task.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, task])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("NoMilestones");
      }
    });

    it("should fail to post task with too many milestones", async () => {
      const task = Keypair.generate();
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      const tooManyMilestones: Milestone[] = Array(11).fill(null).map((_, i) => ({
        description: `Milestone ${i + 1}`,
        amount: new anchor.BN(100000),
        completed: false,
        paid: false,
      }));
      
      try {
        await program.methods
          .postTask("Title", "Description", new anchor.BN(1100000), tooManyMilestones, deadline)
          .accounts({
            owner: client.publicKey,
            task: task.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, task])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("TooManyMilestones");
      }
    });

    it("should fail to post task when milestone amounts don't sum to budget", async () => {
      const task = Keypair.generate();
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      
      const badMilestones: Milestone[] = [
        {
          description: "Milestone 1",
          amount: new anchor.BN(500000),
          completed: false,
          paid: false,
        },
        {
          description: "Milestone 2",
          amount: new anchor.BN(300000),
          completed: false,
          paid: false,
        },
      ]; // Sum is 800000, but budget is 1000000
      
      try {
        await program.methods
          .postTask("Title", "Description", new anchor.BN(1000000), badMilestones, deadline)
          .accounts({
            owner: client.publicKey,
            task: task.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, task])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("MilestoneAmountMismatch");
      }
    });

    it("should fail to post task with deadline in the past", async () => {
      const task = Keypair.generate();
      const pastDeadline = new anchor.BN(Math.floor(Date.now() / 1000) - 1000);
      
      try {
        await program.methods
          .postTask("Title", "Description", new anchor.BN(1000000), milestones, pastDeadline)
          .accounts({
            owner: client.publicKey,
            task: task.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, task])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("InvalidDeadline");
      }
    });
  });

  // ============================================================================
  // BID SUBMISSION TESTS
  // ============================================================================
  
  describe("Bid Submission", () => {
    let client: Keypair;
    let freelancer: Keypair;
    let taskKeypair: Keypair;
    let taskPubkey: PublicKey;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      // Setup client
      client = Keypair.generate();
      let sig = await provider.connection.requestAirdrop(
        client.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      // Setup freelancer
      freelancer = Keypair.generate();
      sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      // Create task
      taskKeypair = Keypair.generate();
      taskPubkey = taskKeypair.publicKey;
      milestones = [
        {
          description: "Initial setup",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
        {
          description: "Development",
          amount: new anchor.BN(2000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      await program.methods
        .postTask("Test Task", "Test Description", new anchor.BN(3000000), milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
    });

    it("should submit a bid with valid parameters", async () => {
      const bid = Keypair.generate();
      const amount = new anchor.BN(2500000);
      const timeline = new anchor.BN(86400 * 5); // 5 days
      const proposal = "I can complete this task efficiently";
      
      await program.methods
        .submitBid(amount, timeline, proposal)
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bid.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bid])
        .rpc();
      
      // Verify bid was created
      const bidAccount = await program.account.bid.fetch(bid.publicKey);
      expect(bidAccount.task.toBase58()).to.equal(taskPubkey.toBase58());
      expect(bidAccount.bidder.toBase58()).to.equal(freelancer.publicKey.toBase58());
      expect(bidAccount.amount.toNumber()).to.equal(amount.toNumber());
      expect(bidAccount.timeline.toNumber()).to.equal(timeline.toNumber());
      expect(bidAccount.proposal).to.equal(proposal);
      expect(getBidStatus(bidAccount.status)).to.equal("Pending");
    });

    it("should fail when task owner tries to bid on own task", async () => {
      const bid = Keypair.generate();
      
      try {
        await program.methods
          .submitBid(new anchor.BN(1000000), new anchor.BN(86400), "Proposal")
          .accounts({
            bidder: client.publicKey,
            task: taskPubkey,
            bid: bid.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, bid])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        // The constraint should fail
        expect(error.toString()).to.include("constraint was violated");
      }
    });

    it("should fail to submit bid with amount equal to zero", async () => {
      const bid = Keypair.generate();
      
      try {
        await program.methods
          .submitBid(new anchor.BN(0), new anchor.BN(86400), "Proposal")
          .accounts({
            bidder: freelancer.publicKey,
            task: taskPubkey,
            bid: bid.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([freelancer, bid])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("InvalidAmount");
      }
    });

    it("should fail to submit bid with timeline equal to zero", async () => {
      const bid = Keypair.generate();
      
      try {
        await program.methods
          .submitBid(new anchor.BN(1000000), new anchor.BN(0), "Proposal")
          .accounts({
            bidder: freelancer.publicKey,
            task: taskPubkey,
            bid: bid.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([freelancer, bid])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("InvalidTimeline");
      }
    });

    it("should fail to submit bid when timeline exceeds task deadline", async () => {
      const bid = Keypair.generate();
      const longTimeline = new anchor.BN(86400 * 10); // 10 days, but task deadline is 7 days
      
      try {
        await program.methods
          .submitBid(new anchor.BN(1000000), longTimeline, "Proposal")
          .accounts({
            bidder: freelancer.publicKey,
            task: taskPubkey,
            bid: bid.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([freelancer, bid])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("TimelineExceedsDeadline");
      }
    });

    it("should fail to submit bid with proposal exceeding max length", async () => {
      const bid = Keypair.generate();
      const longProposal = "a".repeat(MAX_PROPOSAL_LEN + 1);
      
      try {
        await program.methods
          .submitBid(new anchor.BN(1000000), new anchor.BN(86400), longProposal)
          .accounts({
            bidder: freelancer.publicKey,
            task: taskPubkey,
            bid: bid.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([freelancer, bid])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("ProposalTooLong");
      }
    });

    it("should fail to submit bid on non-open task", async () => {
      // First accept a bid to make task InProgress
      const bid1 = Keypair.generate();
      await program.methods
        .submitBid(new anchor.BN(2000000), new anchor.BN(86400), "First bid")
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bid1.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bid1])
        .rpc();
      
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bid1.publicKey,
        })
        .signers([client])
        .rpc();
      
      // Now try to submit another bid
      const anotherFreelancer = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        anotherFreelancer.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      const bid2 = Keypair.generate();
      try {
        await program.methods
          .submitBid(new anchor.BN(1500000), new anchor.BN(43200), "Second bid")
          .accounts({
            bidder: anotherFreelancer.publicKey,
            task: taskPubkey,
            bid: bid2.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([anotherFreelancer, bid2])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });
  });

  // ============================================================================
  // BID ACCEPTANCE TESTS
  // ============================================================================
  
  describe("Bid Acceptance", () => {
    let client: Keypair;
    let freelancer: Keypair;
    let taskKeypair: Keypair;
    let taskPubkey: PublicKey;
    let bidKeypair: Keypair;
    let bidPubkey: PublicKey;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      client = Keypair.generate();
      freelancer = Keypair.generate();
      
      let sig = await provider.connection.requestAirdrop(
        client.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      taskKeypair = Keypair.generate();
      taskPubkey = taskKeypair.publicKey;
      milestones = [
        {
          description: "Milestone 1",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      await program.methods
        .postTask("Task", "Description", new anchor.BN(1000000), milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
      await sleep(500);
      
      bidKeypair = Keypair.generate();
      bidPubkey = bidKeypair.publicKey;
      await program.methods
        .submitBid(new anchor.BN(900000), new anchor.BN(86400 * 3), "My proposal")
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bidKeypair])
        .rpc();
    });

    it("should accept a pending bid by task owner", async () => {
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([client])
        .rpc();
      
      // Verify bid status changed
      const bidAccount = await program.account.bid.fetch(bidPubkey);
      expect(getBidStatus(bidAccount.status)).to.equal("Accepted");
      
      // Verify task updated
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(getTaskStatus(taskAccount.status)).to.equal("InProgress");
      expect(taskAccount.acceptedBid?.toBase58()).to.equal(bidPubkey.toBase58());
    });

    it("should fail when non-owner tries to accept bid", async () => {
      const attacker = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        attacker.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      try {
        await program.methods
          .acceptBid()
          .accounts({
            owner: attacker.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
          })
          .signers([attacker])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });

    it("should fail to accept already accepted bid", async () => {
      // First accept the bid
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([client])
        .rpc();
      
      // Try to accept again
      try {
        await program.methods
          .acceptBid()
          .accounts({
            owner: client.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
          })
          .signers([client])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });
  });

  // ============================================================================
  // BID REJECTION AND WITHDRAWAL TESTS
  // ============================================================================
  
  describe("Bid Rejection and Withdrawal", () => {
    let client: Keypair;
    let freelancer: Keypair;
    let taskKeypair: Keypair;
    let taskPubkey: PublicKey;
    let bidKeypair: Keypair;
    let bidPubkey: PublicKey;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      client = Keypair.generate();
      freelancer = Keypair.generate();
      
      let sig = await provider.connection.requestAirdrop(
        client.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      taskKeypair = Keypair.generate();
      taskPubkey = taskKeypair.publicKey;
      milestones = [
        {
          description: "Milestone 1",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      await program.methods
        .postTask("Task", "Description", new anchor.BN(1000000), milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
      
      bidKeypair = Keypair.generate();
      bidPubkey = bidKeypair.publicKey;
      await program.methods
        .submitBid(new anchor.BN(900000), new anchor.BN(86400 * 3), "My proposal")
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bidKeypair])
        .rpc();
    });

    it("should reject a pending bid by task owner", async () => {
      await program.methods
        .rejectBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([client])
        .rpc();
      
      const bidAccount = await program.account.bid.fetch(bidPubkey);
      expect(getBidStatus(bidAccount.status)).to.equal("Rejected");
    });

    it("should fail when non-owner tries to reject bid", async () => {
      try {
        await program.methods
          .rejectBid()
          .accounts({
            owner: freelancer.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
          })
          .signers([freelancer])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });

    it("should withdraw a pending bid by bidder", async () => {
      await program.methods
        .withdrawBid()
        .accounts({
          bidder: freelancer.publicKey,
          bid: bidPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer])
        .rpc();
      
      // Bid account should be closed
      try {
        await program.account.bid.fetch(bidPubkey);
        expect.fail("Bid should have been closed");
      } catch (error: any) {
        expect(error.toString()).to.include("Account does not exist");
      }
    });

    it("should fail when non-bidder tries to withdraw bid", async () => {
      const attacker = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        attacker.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      try {
        await program.methods
          .withdrawBid()
          .accounts({
            bidder: attacker.publicKey,
            bid: bidPubkey,
            systemProgram: SystemProgram.programId,
          })
          .signers([attacker])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });
  });

  // ============================================================================
  // TASK UPDATE TESTS
  // ============================================================================
  
  describe("Task Update", () => {
    let client: Keypair;
    let taskKeypair: Keypair;
    let taskPubkey: PublicKey;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      client = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        client.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      taskKeypair = Keypair.generate();
      taskPubkey = taskKeypair.publicKey;
      milestones = [
        {
          description: "Milestone 1",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      await program.methods
        .postTask("Original Title", "Original Description", new anchor.BN(1000000), milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
    });

    it("should update task description", async () => {
      const newDescription = "Updated Description";
      
      await program.methods
        .updateTask(newDescription, null, null)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
        })
        .signers([client])
        .rpc();
      
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(taskAccount.description).to.equal(newDescription);
    });

    it("should update task budget", async () => {
      const newBudget = new anchor.BN(2000000);
      
      await program.methods
        .updateTask(null, newBudget, null)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
        })
        .signers([client])
        .rpc();
      
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(taskAccount.budget.toNumber()).to.equal(newBudget.toNumber());
    });

    it("should update task deadline", async () => {
      const newDeadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 14);
      
      await program.methods
        .updateTask(null, null, newDeadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
        })
        .signers([client])
        .rpc();
      
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(taskAccount.deadline.toNumber()).to.equal(newDeadline.toNumber());
    });

    it("should fail to update task when not owner", async () => {
      const attacker = Keypair.generate();
      const sig = await provider.connection.requestAirdrop(
        attacker.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      try {
        await program.methods
          .updateTask("Hacked", null, null)
          .accounts({
            owner: attacker.publicKey,
            task: taskPubkey,
          })
          .signers([attacker])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });

    it("should fail to update non-open task", async () => {
      // First accept a bid to make task InProgress
      const freelancer = Keypair.generate();
      let sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      
      const bid = Keypair.generate();
      await program.methods
        .submitBid(new anchor.BN(900000), new anchor.BN(86400), "Proposal")
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bid.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bid])
        .rpc();
      
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bid.publicKey,
        })
        .signers([client])
        .rpc();
      
      // Try to update
      try {
        await program.methods
          .updateTask("Updated", null, null)
          .accounts({
            owner: client.publicKey,
            task: taskPubkey,
          })
          .signers([client])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });
  });

  // ============================================================================
  // TASK CANCELLATION TESTS
  // ============================================================================
  
  describe("Task Cancellation", () => {
    let client: Keypair;
    let freelancer: Keypair;
    let taskKeypair: Keypair;
    let taskPubkey: PublicKey;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      client = Keypair.generate();
      freelancer = Keypair.generate();
      
      let sig = await provider.connection.requestAirdrop(
        client.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        5 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      taskKeypair = Keypair.generate();
      taskPubkey = taskKeypair.publicKey;
      milestones = [
        {
          description: "Milestone 1",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      await program.methods
        .postTask("Task", "Description", new anchor.BN(1000000), milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
    });

    it("should cancel an open task without escrow", async () => {
      await program.methods
        .cancelTask()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
        })
        .signers([client])
        .rpc();
      
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(getTaskStatus(taskAccount.status)).to.equal("Cancelled");
    });

    it("should fail to cancel task when not owner", async () => {
      try {
        await program.methods
          .cancelTask()
          .accounts({
            owner: freelancer.publicKey,
            task: taskPubkey,
          })
          .signers([freelancer])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });

    it("should fail to cancel task with escrow", async () => {
      // Accept bid and fund escrow first
      const bid = Keypair.generate();
      await program.methods
        .submitBid(new anchor.BN(900000), new anchor.BN(86400), "Proposal")
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bid.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bid])
        .rpc();
      
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bid.publicKey,
        })
        .signers([client])
        .rpc();
      
      // Create token mint and fund escrow (simplified - in real test would need token setup)
      // For this test, we verify the constraint works by checking escrow_account
      // The escrow test below covers the full flow
    });
  });

  // ============================================================================
  // ESCROW AND TOKEN TESTS
  // ============================================================================
  
  describe("Escrow and Payment Flow", () => {
    let client: Keypair;
    let freelancer: Keypair;
    let taskKeypair: Keypair;
    let taskPubkey: PublicKey;
    let bidKeypair: Keypair;
    let bidPubkey: PublicKey;
    let tokenMint: PublicKey;
    let clientTokenAccount: PublicKey;
    let freelancerTokenAccount: PublicKey;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      client = Keypair.generate();
      freelancer = Keypair.generate();
      
      let sig = await provider.connection.requestAirdrop(
        client.publicKey,
        10 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        10 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      // Create token mint
      tokenMint = await createMint(
        provider.connection,
        client,
        client.publicKey,
        null,
        6
      );
      
      // Create token accounts
      clientTokenAccount = await createAccount(
        provider.connection,
        client,
        tokenMint,
        client.publicKey
      );
      
      freelancerTokenAccount = await createAccount(
        provider.connection,
        freelancer,
        tokenMint,
        freelancer.publicKey
      );
      
      // Mint tokens to client
      await mintTo(
        provider.connection,
        client,
        tokenMint,
        clientTokenAccount,
        client.publicKey,
        10000000
      );
      
      taskKeypair = Keypair.generate();
      taskPubkey = taskKeypair.publicKey;
      milestones = [
        {
          description: "Milestone 1",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
        {
          description: "Milestone 2",
          amount: new anchor.BN(2000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      await program.methods
        .postTask("Task", "Description", new anchor.BN(3000000), milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
      
      bidKeypair = Keypair.generate();
      bidPubkey = bidKeypair.publicKey;
      await program.methods
        .submitBid(new anchor.BN(3000000), new anchor.BN(86400 * 5), "My proposal")
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bidKeypair])
        .rpc();
      
      // Accept bid
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([client])
        .rpc();
    });

    it("should fund escrow with tokens", async () => {
      // Derive escrow PDA
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskPubkey.toBuffer()],
        program.programId
      );
      
      // Derive escrow token account PDA
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          acceptedBid: bidPubkey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      // Verify escrow was created
      const escrowAccount = await program.account.escrow.fetch(escrowPda);
      expect(escrowAccount.task.toBase58()).to.equal(taskPubkey.toBase58());
      expect(escrowAccount.client.toBase58()).to.equal(client.publicKey.toBase58());
      expect(escrowAccount.freelancer.toBase58()).to.equal(freelancer.publicKey.toBase58());
      expect(escrowAccount.totalAmount.toNumber()).to.equal(3000000);
      expect(escrowAccount.releasedAmount.toNumber()).to.equal(0);
      expect(escrowAccount.tokenMint.toBase58()).to.equal(tokenMint.toBase58());
      
      // Verify tokens were transferred
      const escrowTokenBalance = await getAccount(provider.connection, escrowTokenPda);
      expect(Number(escrowTokenBalance.amount)).to.equal(3000000);
      
      const clientBalance = await getAccount(provider.connection, clientTokenAccount);
      expect(Number(clientBalance.amount)).to.equal(7000000); // Started with 10M, transferred 3M
    });

    it("should complete a milestone", async () => {
      await program.methods
        .completeMilestone(0)
        .accounts({
          freelancer: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([freelancer])
        .rpc();
      
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(taskAccount.milestones[0].completed).to.be.true;
      expect(taskAccount.milestones[1].completed).to.be.false;
    });

    it("should release payment for completed milestone", async () => {
      // First fund escrow
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskPubkey.toBuffer()],
        program.programId
      );
      
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          acceptedBid: bidPubkey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      // Complete milestone
      await program.methods
        .completeMilestone(0)
        .accounts({
          freelancer: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([freelancer])
        .rpc();
      
      // Release payment
      await program.methods
        .releasePayment(0)
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          escrow: escrowPda,
          escrowTokenAccount: escrowTokenPda,
          freelancerTokenAccount: freelancerTokenAccount,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([client])
        .rpc();
      
      // Verify payment was released
      const escrowAccount = await program.account.escrow.fetch(escrowPda);
      expect(escrowAccount.releasedAmount.toNumber()).to.equal(1000000);
      
      const freelancerBalance = await getAccount(provider.connection, freelancerTokenAccount);
      expect(Number(freelancerBalance.amount)).to.equal(1000000);
      
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(taskAccount.milestones[0].paid).to.be.true;
    });

    it("should fail to release payment for uncompleted milestone", async () => {
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskPubkey.toBuffer()],
        program.programId
      );
      
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          acceptedBid: bidPubkey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      // Try to release without completing milestone
      try {
        await program.methods
          .releasePayment(0)
          .accounts({
            client: client.publicKey,
            task: taskPubkey,
            escrow: escrowPda,
            escrowTokenAccount: escrowTokenPda,
            freelancerTokenAccount: freelancerTokenAccount,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([client])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("MilestoneNotCompleted");
      }
    });

    it("should fail to release payment twice for same milestone", async () => {
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskPubkey.toBuffer()],
        program.programId
      );
      
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          acceptedBid: bidPubkey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      // Complete and release
      await program.methods
        .completeMilestone(0)
        .accounts({
          freelancer: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([freelancer])
        .rpc();
      
      await program.methods
        .releasePayment(0)
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          escrow: escrowPda,
          escrowTokenAccount: escrowTokenPda,
          freelancerTokenAccount: freelancerTokenAccount,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([client])
        .rpc();
      
      // Try to release again
      try {
        await program.methods
          .releasePayment(0)
          .accounts({
            client: client.publicKey,
            task: taskPubkey,
            escrow: escrowPda,
            escrowTokenAccount: escrowTokenPda,
            freelancerTokenAccount: freelancerTokenAccount,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([client])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("MilestoneAlreadyPaid");
      }
    });

    it("should request refund for cancelled task", async () => {
      // Fund escrow
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskPubkey.toBuffer()],
        program.programId
      );
      
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          acceptedBid: bidPubkey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      // Update task status to cancelled (in a real scenario this would happen via dispute resolution)
      // For this test, we verify the escrow logic is correct
      
      // Get initial client balance
      const initialClientBalance = await getAccount(provider.connection, clientTokenAccount);
      
      // Request refund
      await program.methods
        .requestRefund()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          escrow: escrowPda,
          escrowTokenAccount: escrowTokenPda,
          clientTokenAccount: clientTokenAccount,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([client])
        .rpc();
      
      // Verify refund was received
      const finalClientBalance = await getAccount(provider.connection, clientTokenAccount);
      expect(Number(finalClientBalance.amount) - Number(initialClientBalance.amount)).to.equal(3000000);
    });

    it("should complete full payment flow and mark task as completed", async () => {
      // Fund escrow
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskPubkey.toBuffer()],
        program.programId
      );
      
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          acceptedBid: bidPubkey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      // Complete and release both milestones
      for (let i = 0; i < 2; i++) {
        await program.methods
          .completeMilestone(i)
          .accounts({
            freelancer: freelancer.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
          })
          .signers([freelancer])
          .rpc();
        
        await program.methods
          .releasePayment(i)
          .accounts({
            client: client.publicKey,
            task: taskPubkey,
            escrow: escrowPda,
            escrowTokenAccount: escrowTokenPda,
            freelancerTokenAccount: freelancerTokenAccount,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([client])
          .rpc();
      }
      
      // Verify task is completed
      const taskAccount = await program.account.task.fetch(taskPubkey);
      expect(getTaskStatus(taskAccount.status)).to.equal("Completed");
      
      // Verify freelancer received full payment
      const freelancerBalance = await getAccount(provider.connection, freelancerTokenAccount);
      expect(Number(freelancerBalance.amount)).to.equal(3000000);
    });
  });

  // ============================================================================
  // REVIEW SUBMISSION TESTS
  // ============================================================================
  
  describe("Review Submission", () => {
    let client: Keypair;
    let freelancer: Keypair;
    let taskKeypair: Keypair;
    let taskPubkey: PublicKey;
    let bidKeypair: Keypair;
    let bidPubkey: PublicKey;
    let milestones: Milestone[];
    
    beforeEach(async () => {
      client = Keypair.generate();
      freelancer = Keypair.generate();
      
      let sig = await provider.connection.requestAirdrop(
        client.publicKey,
        10 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        10 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      await sleep(500);
      
      // Initialize profiles for both parties
      const [clientProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), client.publicKey.toBuffer()],
        program.programId
      );
      
      const [freelancerProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), freelancer.publicKey.toBuffer()],
        program.programId
      );
      
      await program.methods
        .initializeAgentProfile("Client")
        .accounts({
          owner: client.publicKey,
          profile: clientProfilePda,
          systemProgram: SystemProgram.programId,
        })
        .signers([client])
        .rpc();
      
      await program.methods
        .initializeAgentProfile("Freelancer")
        .accounts({
          owner: freelancer.publicKey,
          profile: freelancerProfilePda,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer])
        .rpc();
      
      taskKeypair = Keypair.generate();
      taskPubkey = taskKeypair.publicKey;
      milestones = [
        {
          description: "Milestone 1",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 7);
      await program.methods
        .postTask("Task", "Description", new anchor.BN(1000000), milestones, deadline)
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
      
      bidKeypair = Keypair.generate();
      bidPubkey = bidKeypair.publicKey;
      await program.methods
        .submitBid(new anchor.BN(1000000), new anchor.BN(86400), "Proposal")
        .accounts({
          bidder: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bidKeypair])
        .rpc();
      
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([client])
        .rpc();
    });

    it("should submit review by client for completed task", async () => {
      // Create a mock completed task by updating status directly via completing milestones
      // First, fund escrow with tokens
      const tokenMint = await createMint(provider.connection, client, client.publicKey, null, 6);
      const clientTokenAccount = await createAccount(provider.connection, client, tokenMint, client.publicKey);
      const freelancerTokenAccount = await createAccount(provider.connection, freelancer, tokenMint, freelancer.publicKey);
      
      await mintTo(provider.connection, client, tokenMint, clientTokenAccount, client.publicKey, 10000000);
      
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskPubkey.toBuffer()],
        program.programId
      );
      
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          acceptedBid: bidPubkey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      // Complete milestone and release payment to mark task completed
      await program.methods
        .completeMilestone(0)
        .accounts({
          freelancer: freelancer.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
        })
        .signers([freelancer])
        .rpc();
      
      await program.methods
        .releasePayment(0)
        .accounts({
          client: client.publicKey,
          task: taskPubkey,
          escrow: escrowPda,
          escrowTokenAccount: escrowTokenPda,
          freelancerTokenAccount: freelancerTokenAccount,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([client])
        .rpc();
      
      // Submit review
      const review = Keypair.generate();
      const rating = 5;
      const reviewText = "Excellent work! Highly recommended.";
      
      const [freelancerProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), freelancer.publicKey.toBuffer()],
        program.programId
      );
      
      await program.methods
        .submitReview(rating, reviewText)
        .accounts({
          reviewer: client.publicKey,
          task: taskPubkey,
          bid: bidPubkey,
          reviewee: freelancer.publicKey,
          revieweeProfile: freelancerProfilePda,
          review: review.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, review])
        .rpc();
      
      // Verify review was created
      const reviewAccount = await program.account.review.fetch(review.publicKey);
      expect(reviewAccount.reviewer.toBase58()).to.equal(client.publicKey.toBase58());
      expect(reviewAccount.reviewee.toBase58()).to.equal(freelancer.publicKey.toBase58());
      expect(reviewAccount.task.toBase58()).to.equal(taskPubkey.toBase58());
      expect(reviewAccount.rating).to.equal(rating);
      expect(reviewAccount.reviewText).to.equal(reviewText);
      
      // Verify profile was updated with rating
      const freelancerProfile = await program.account.agentProfile.fetch(freelancerProfilePda);
      expect(freelancerProfile.ratingSum).to.equal(rating);
      expect(freelancerProfile.ratingCount).to.equal(1);
    });

    it("should fail to submit review for non-completed task", async () => {
      const review = Keypair.generate();
      const [freelancerProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), freelancer.publicKey.toBuffer()],
        program.programId
      );
      
      try {
        await program.methods
          .submitReview(5, "Great work")
          .accounts({
            reviewer: client.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
            reviewee: freelancer.publicKey,
            revieweeProfile: freelancerProfilePda,
            review: review.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, review])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("constraint was violated");
      }
    });

    it("should fail to submit review with invalid rating (0)", async () => {
      const review = Keypair.generate();
      const [freelancerProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), freelancer.publicKey.toBuffer()],
        program.programId
      );
      
      try {
        await program.methods
          .submitReview(0, "Bad rating")
          .accounts({
            reviewer: client.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
            reviewee: freelancer.publicKey,
            revieweeProfile: freelancerProfilePda,
            review: review.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, review])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("InvalidRating");
      }
    });

    it("should fail to submit review with invalid rating (6)", async () => {
      const review = Keypair.generate();
      const [freelancerProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), freelancer.publicKey.toBuffer()],
        program.programId
      );
      
      try {
        await program.methods
          .submitReview(6, "Bad rating")
          .accounts({
            reviewer: client.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
            reviewee: freelancer.publicKey,
            revieweeProfile: freelancerProfilePda,
            review: review.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, review])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("InvalidRating");
      }
    });

    it("should fail to submit review with text exceeding max length", async () => {
      const review = Keypair.generate();
      const [freelancerProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), freelancer.publicKey.toBuffer()],
        program.programId
      );
      
      const longReview = "a".repeat(MAX_REVIEW_LEN + 1);
      
      try {
        await program.methods
          .submitReview(5, longReview)
          .accounts({
            reviewer: client.publicKey,
            task: taskPubkey,
            bid: bidPubkey,
            reviewee: freelancer.publicKey,
            revieweeProfile: freelancerProfilePda,
            review: review.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([client, review])
          .rpc();
        expect.fail("Should have thrown an error");
      } catch (error: any) {
        expect(error.toString()).to.include("ReviewTooLong");
      }
    });

    it("should fail when user tries to review themselves", async () => {
      // This is covered by the constraint that reviewer != reviewee
      // But we'd need a completed task to test it properly
    });
  });

  // ============================================================================
  // INTEGRATION TEST - COMPLETE WORKFLOW
  // ============================================================================
  
  describe("Complete Workflow Integration", () => {
    it("should execute full marketplace workflow", async () => {
      // Step 1: Setup participants
      const client = Keypair.generate();
      const freelancer = Keypair.generate();
      
      let sig = await provider.connection.requestAirdrop(
        client.publicKey,
        10 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      
      sig = await provider.connection.requestAirdrop(
        freelancer.publicKey,
        10 * anchor.web3.LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
      
      // Step 2: Initialize profiles
      const [clientProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), client.publicKey.toBuffer()],
        program.programId
      );
      
      const [freelancerProfilePda] = PublicKey.findProgramAddressSync(
        [Buffer.from("profile"), freelancer.publicKey.toBuffer()],
        program.programId
      );
      
      await program.methods
        .initializeAgentProfile("Tech Startup Client")
        .accounts({
          owner: client.publicKey,
          profile: clientProfilePda,
          systemProgram: SystemProgram.programId,
        })
        .signers([client])
        .rpc();
      
      await program.methods
        .initializeAgentProfile("Expert Freelancer")
        .accounts({
          owner: freelancer.publicKey,
          profile: freelancerProfilePda,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer])
        .rpc();
      
      // Step 3: Client posts a task
      const taskKeypair = Keypair.generate();
      const milestones: Milestone[] = [
        {
          description: "Design and architecture",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
        {
          description: "Implementation",
          amount: new anchor.BN(3000000),
          completed: false,
          paid: false,
        },
        {
          description: "Testing and deployment",
          amount: new anchor.BN(1000000),
          completed: false,
          paid: false,
        },
      ];
      
      const deadline = new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 14);
      
      await program.methods
        .postTask(
          "Build DeFi Dashboard",
          "Create a comprehensive DeFi dashboard with real-time data visualization",
          new anchor.BN(5000000),
          milestones,
          deadline
        )
        .accounts({
          owner: client.publicKey,
          task: taskKeypair.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, taskKeypair])
        .rpc();
      
      let task = await program.account.task.fetch(taskKeypair.publicKey);
      expect(task.title).to.equal("Build DeFi Dashboard");
      expect(getTaskStatus(task.status)).to.equal("Open");
      
      // Step 4: Freelancer submits bid
      const bidKeypair = Keypair.generate();
      
      await program.methods
        .submitBid(
          new anchor.BN(4500000),
          new anchor.BN(86400 * 10),
          "I have 5 years of experience building DeFi applications. I can deliver this in 10 days with high quality."
        )
        .accounts({
          bidder: freelancer.publicKey,
          task: taskKeypair.publicKey,
          bid: bidKeypair.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, bidKeypair])
        .rpc();
      
      let bid = await program.account.bid.fetch(bidKeypair.publicKey);
      expect(getBidStatus(bid.status)).to.equal("Pending");
      expect(bid.amount.toNumber()).to.equal(4500000);
      
      // Step 5: Client accepts bid
      await program.methods
        .acceptBid()
        .accounts({
          owner: client.publicKey,
          task: taskKeypair.publicKey,
          bid: bidKeypair.publicKey,
        })
        .signers([client])
        .rpc();
      
      task = await program.account.task.fetch(taskKeypair.publicKey);
      expect(getTaskStatus(task.status)).to.equal("InProgress");
      
      bid = await program.account.bid.fetch(bidKeypair.publicKey);
      expect(getBidStatus(bid.status)).to.equal("Accepted");
      
      // Step 6: Fund escrow
      const tokenMint = await createMint(provider.connection, client, client.publicKey, null, 6);
      const clientTokenAccount = await createAccount(provider.connection, client, tokenMint, client.publicKey);
      const freelancerTokenAccount = await createAccount(provider.connection, freelancer, tokenMint, freelancer.publicKey);
      
      await mintTo(provider.connection, client, tokenMint, clientTokenAccount, client.publicKey, 10000000);
      
      const [escrowPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow"), taskKeypair.publicKey.toBuffer()],
        program.programId
      );
      
      const [escrowTokenPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("escrow_token"), escrowPda.toBuffer()],
        program.programId
      );
      
      await program.methods
        .fundEscrow()
        .accounts({
          client: client.publicKey,
          task: taskKeypair.publicKey,
          acceptedBid: bidKeypair.publicKey,
          escrow: escrowPda,
          clientTokenAccount: clientTokenAccount,
          escrowTokenAccount: escrowTokenPda,
          tokenMint: tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([client])
        .rpc();
      
      let escrow = await program.account.escrow.fetch(escrowPda);
      expect(escrow.totalAmount.toNumber()).to.equal(4500000);
      
      // Step 7: Complete milestones and release payments
      for (let i = 0; i < 3; i++) {
        await program.methods
          .completeMilestone(i)
          .accounts({
            freelancer: freelancer.publicKey,
            task: taskKeypair.publicKey,
            bid: bidKeypair.publicKey,
          })
          .signers([freelancer])
          .rpc();
        
        await program.methods
          .releasePayment(i)
          .accounts({
            client: client.publicKey,
            task: taskKeypair.publicKey,
            escrow: escrowPda,
            escrowTokenAccount: escrowTokenPda,
            freelancerTokenAccount: freelancerTokenAccount,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([client])
          .rpc();
      }
      
      task = await program.account.task.fetch(taskKeypair.publicKey);
      expect(getTaskStatus(task.status)).to.equal("Completed");
      
      const freelancerBalance = await getAccount(provider.connection, freelancerTokenAccount);
      expect(Number(freelancerBalance.amount)).to.equal(4500000);
      
      // Step 8: Submit mutual reviews
      const clientReview = Keypair.generate();
      const freelancerReview = Keypair.generate();
      
      await program.methods
        .submitReview(5, "Excellent work! Delivered on time with great quality.")
        .accounts({
          reviewer: client.publicKey,
          task: taskKeypair.publicKey,
          bid: bidKeypair.publicKey,
          reviewee: freelancer.publicKey,
          revieweeProfile: freelancerProfilePda,
          review: clientReview.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([client, clientReview])
        .rpc();
      
      await program.methods
        .submitReview(5, "Great client! Clear requirements and prompt payment.")
        .accounts({
          reviewer: freelancer.publicKey,
          task: taskKeypair.publicKey,
          bid: bidKeypair.publicKey,
          reviewee: client.publicKey,
          revieweeProfile: clientProfilePda,
          review: freelancerReview.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([freelancer, freelancerReview])
        .rpc();
      
      // Verify profiles updated with ratings
      const clientProfile = await program.account.agentProfile.fetch(clientProfilePda);
      const freelancerProfile = await program.account.agentProfile.fetch(freelancerProfilePda);
      
      expect(clientProfile.ratingSum).to.equal(5);
      expect(clientProfile.ratingCount).to.equal(1);
      expect(freelancerProfile.ratingSum).to.equal(5);
      expect(freelancerProfile.ratingCount).to.equal(1);
      
      console.log("✅ Complete marketplace workflow executed successfully!");
    });
  });
});
